using Domain.Enums;

namespace Domain.Entities
{
    public class Payment : BaseEntity
    {
        public Guid StudentId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; } = default!;
        public PaymentType PaymentType { get; set; }
        public PaymentStatus Status { get; set; } = PaymentStatus.Pending;

        // Unique reference generated by the system, used for both payment types
        public string PaymentReference { get; set; } = default!;

        // Paystack-specific
        public string? PaystackReference { get; set; }
        public string? PaystackAuthorizationUrl { get; set; }
        public string? PaystackAccessCode { get; set; }

        // Manual payment details submitted by the student
        public string? BankName { get; set; }
        public string? AccountName { get; set; }
        public string? AccountNumber { get; set; }
        public string? PayerName { get; set; }

        // Admin confirmation / rejection
        public string? ConfirmedBy { get; set; }
        public DateTime? ConfirmedAt { get; set; }
        public string? RejectionReason { get; set; }

        // Navigation
        public Student Student { get; set; } = default!;
    }
}
